@SmartBudget.TransactionsService.API_HostAddress = https://localhost:7291

POST {{SmartBudget.TransactionsService.API_HostAddress}}/api/transactions
Content-Type: application/json

{
    "amount": 52,
    "note": "transport fee",
    "date": "2005-10-11",
    "categoryId": 3
}
###
